### ISSUE TITLE
Best image for build agent

### ISSUE THREAD

**Issue by damiensawyer** [g0t4/aspnetcore-generator-api#1]
Hi, Thanks for this project. 

I can't seem to find aspnetcore/teamcity-agent-with-compose at hub.docker.com. Has it been deprecated? Is there something else that I should be using instead?

Cheers :-)

**Comment by damiensawyer** [comment]
I just realised that you are running   build: ./agent and, I assume, making your own image.

**Comment by g0t4** [comment]
Yes, just a local image. How's the course coming for you?

**Comment by damiensawyer** [comment]
Hey,

Man - I'm loving it!! The pipeline you've set up is great.

I thought that I'd have a crack at setting up a TeamCity, a registry and
SonarQube behind nginx - all in Docker, and try to get it running on a VM.
It's working locally but failing in the cloud. I guess that nutting stuff
out like this is where you really learn.

Thanks for your work :-).



------------------------------------------------------------------------
I welcome VSRE emails. Learn more at vsre.info
------------------------------------------------------------------------

**Comment by g0t4** [comment]
Yup, get the hands dirty. You know you've learned something when it's
providing value to you.
